apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "voting-app.fullname" . }}-config
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ include "voting-app.fullname" . }}-redis
  REDIS_PORT: {{ .Values.redis.service.port | quote }}
  POSTGRES_HOST: {{ include "voting-app.fullname" . }}-postgres
  POSTGRES_PORT: {{ .Values.postgres.service.port | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  OPTION_A: {{ .Values.vote.options.a | quote }}
  OPTION_B: {{ .Values.vote.options.b | quote }}
