apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "voting-app.fullname" . }}-worker
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "voting-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "voting-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      automountServiceAccountToken: false
      serviceAccountName: {{ include "voting-app.serviceAccountName" (dict "root" . "component" "worker") }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
        runAsNonRoot: true
        runAsUser: 10003
        runAsGroup: 10003
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "voting-app.fullname" . }}-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "voting-app.fullname" . }}-postgres
                  key: POSTGRES_PASSWORD
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
